# Usamos una imagen base de Python
FROM python:3.10

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de requerimientos
COPY requirements.txt requirements.txt

# Instalamos las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos el código de la aplicación
COPY . .

# Establecemos las variables de entorno
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=fizzy.settings  

# Exponemos el puerto de la aplicación (normalmente 8000)
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
