# Generated by Django 5.1.1 on 2024-09-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ventas',
            field=models.IntegerField(default=0),
        ),
    ]
